blog/urls.py
from django.urls import path
from . import views

#add the url pattern for the view that will correspond to list of posts

urlpatterns = [
    path('',views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/<pk>/publish/', views.post_publish, name='post_publish'),
    path('post/<pk>/remove/', views.post_remove, name='post_remove'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
    path('register/', views.register, name='register'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    path('', include('blog.urls')),

]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

class Comment(models.Model):
    post = models.ForeignKey('blog.post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from .models import Post, Comment
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# django provides the basic form structure and we create a PostForm object
# that uses a specific type of form called ModelForm
# A ModelForm converts the data from the form into a model object, which in this case is the Post object
class PostForm(forms.ModelForm):
    # I do not know what the meta means, but it is part of the syntax for the form
    class Meta:
        # Later on, we can access the Post.title and Post.text in the html for displaying purposes
        model = Post
        fields = ('title','text',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author','text')

#User creation form

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username','email','password1','password2')

blog/views.py
from django.shortcuts import redirect
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.utils import timezone
from .forms import PostForm, CommentForm, RegisterForm
from django.contrib.auth.decorators import login_required
import pdb

# Create your views here.
# View for list of posts

def post_list(request):
    #posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    #This returns a QuerySet that is used by Django to display the data on the actual page

    #posts = Post.objects.order_by('-published_date')

    # This one will only show those entries which have a published time associated with them
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

    # request is the address that the user types in. To this we append the name in second argument and the last part
    # says what the contents are, in this case, multiple posts or list of posts.

    return render(request, 'blog/post_list.html', {'posts':posts})

# view for post detail page

def post_detail(request, pk):
    #Using this function, we will be dirceted to a 404 not found page if the particular address does not correspond to a
    #primary key in the DB for the entries of the blog post

    post = get_object_or_404(Post, pk=pk)
    #pdb.set_trace()
    #Here the content is a singular post so that makes the last argument different from the one before.

    return render(request, 'blog/post_detail.html', {'post': post})

# view for add new post page

@login_required
def post_new(request):
    # POST is one of the methods in html for the data received from user on the page.

    if request.method == "POST":

        # request is where the information entered in the form is stored. Here we create a PostForm object
        # using the data from the form

        form = PostForm(request.POST)

        # Django has its own set of validations that makes sure the fields are not empty etc

        if form.is_valid():

            # We save but do not commit here because there are two attributes of post object that the user does not provide
            # in the form. We provide those in next two lines and then save again in the end.

            post = form.save(commit=False)
            post.author = request.user
            # Commenting the line below to implement save as draft by removing the published date attribute temporarily
            # until it is to be published
            # post.published_date = timezone.now()
            post.save()

            # redirect is a function that will, upon saving of the entered information, redirect to a different link
            # which in this case is the post_detail page that lists all the blog entries.

            return redirect('post_detail', pk=post.pk)
    else:

        # This is the default view, an empty form, if the user goes to the page for the first time.
        # Note: this page has two views: the empty one and then the one after pressing submit.

        form = PostForm()

        # Here the content we are dealing with is an object of form form and not post, therefore the change in last argument

    return render(request, 'blog/post_edit.html', {'form': form})

# view for blog edit

@login_required
def post_edit(request, pk):

    # This view is mostly the same as creating a new post with the difference that in case no changes are made
    # we use instance=post to mean that we re-create the object with the existing data so that it is not lost.

    post = get_object_or_404(Post, pk=pk)
    if request.method=="POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            # post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

# View for the page that shows the unpublished drafts

@login_required
def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    return render(request, 'blog/post_draft_list.html', {'posts': posts})

# This is the view for the publish page for drafts

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    #pdb.set_trace()
    post.publish()
    #return render(request,'blog/post_detail.html', {'post': post})
    return redirect('post_detail', pk=pk)

# Delete post view

@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    #No need pk for redirect to list of post because it is all of the posts
    return redirect('post_list')

# Add a comment on a post

def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)

            comment.post = post
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()

    return render(request, 'blog/add_comment_to_post.html', {'form': form})

# for comment approval and deletion

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('post_detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('post_detail', pk=comment.post.pk)

#View for register page

def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('post_list')
        else:
            form = RegisterForm()
    else:
        form = RegisterForm()
    return render(request, 'blog/register.html', {'form': form})

blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}

{% block content %}
  <h1>New Comment</h1>
  <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-secondary">Send</button>
  </form>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Django Girls blog</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
        <header class="page-header">
            <div class="container">
                {% if user.is_authenticated %}
                    {% if perms.auth.change_post %}
                    <a href="{% url 'post_new' %}" class="top-menu"><span class="bi bi-plus-square"></span></a>
                    <a href="{% url 'post_draft_list' %}" class="top-menu"><span class="bi bi-pencil"></span></a>
                    {% endif %}
                <h3 class="top-menu">Hello {{ user.username }} ! <small><a class="btn btn-default" href="{% url 'logout' %}">Log-Out</a></small></h3>
                {% else %}
                    <h3 class="top-menu"><a href="{% url 'login' %}" class="btn btn-default">Login</a> <a class="btn btn-default" href="{% url 'register' %}">Register</a></h3>
                {% endif %}

                <h1><a href="/">Django Girls Blog</a></h1>
            </div>
        </header>

        <main class="container">
    <div class="row">
        <div class="col">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</main>
    </body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <article class="post">
        {% if perms.auth.change_post %}
        <aside class="actions">
          {% if user.is_authenticated %}
                    <a class="btn btn-secondary" href="{% url 'post_edit' pk=post.pk %}">{% include './icons/pencil-fill.svg' %}</a>
                <a class="btn btn-secondary" href="{% url 'post_remove' pk=post.pk %}"><span class="bi bi-trash"></span></a>
        </aside>
        {% endif %}
                    {% if post.published_date %}
                        <div class="date">{{ post.published_date }}</div>
                    {% else %}
                            <aside class="actions">
                            <a class="btn btn-secondary" href="{% url 'post_publish' pk=post.pk %}">Publish</a>
                            </aside>
                    {% endif %}
            {% endif %}
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
    </article>

    <hr>
    <a class="btn btn-secondary" href="{% url 'add_comment_to_post' pk=post.pk %}">Add Comment</a>
    {% for comment in post.comments.all %}
    <div class="comment">
        <div class="date">
            {{ comment.created_date }}
            {% if not comment.approved_comment %}
                {% if perms.auth.change_comment %}
                <a class="btn btn-secondary" href="{% url 'comment_remove' pk=comment.pk %}">Remove Comment</a>
                <a class="btn btn-secondary" href="{% url 'comment_approve' pk=comment.pk %}">Approve Comment</a>
                {% endif %}
            {% endif %}
        </div>
        <strong>{{ comment.author }}</strong>
        <p>{{ comment.text|linebreaks }}</p>
    </div>
    {% empty %}
        <p>No comments here yet :(</p>
{% endfor %}
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{ post.created_date|date:'d-m-Y' }}</p>
            <h2><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>new post</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-secondary">Save</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <article class="post">
            <time class="date">
                {{ post.published_date }}
            </time>
            <h2><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.text|linebreaksbr }}</p>
            <a class="btn btn-secondary" href ="{% url 'post_detail' pk=post.pk %}">Comments: {{ post.approved_comments.count }}</a>
        </article>
    {% endfor %}
{% endblock %}

blog/templates/blog/register.html
{% extends 'blog/base.html' %}

{% block content %}
    <h2>Register Now</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-secondary">Submit</button>
    </form>
{% endblock %}